import uuid
from typing import List, TypeVar, Generic

from pydantic import BaseModel, Field


class MinimalSource(BaseModel):
    """
    Represents a specific location within a source file.

    Attributes:
        file_path: The relative path to the file.
        first_character_index: The starting character position of the chunk.
        last_character_index: The ending character position of the chunk.
    """

    file_path: str
    first_character_index: int
    last_character_index: int


class UnansweredQuestion(BaseModel):
    """
    Represents a question that has not yet been processed by the RAG system.

    Attributes:
        question_id: A unique identifier for the question (UUID4 by default).
        question: The natural language question text.
    """

    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str


class AnsweredQuestion(UnansweredQuestion):
    """
    Represents a question accompanied by its ground truth answer and sources.

    Attributes:
        sources: A list of MinimalSource objects defining where the answer
            is found.
        answer: The expected ground truth answer.
    """

    sources: List[MinimalSource]
    answer: str


class RagDataset(BaseModel):
    """
    A container for a collection of RAG-related questions.

    Attributes:
        rag_questions: A list containing either answered or unanswered
            questions.
    """

    rag_questions: List[AnsweredQuestion | UnansweredQuestion]


class MinimalSearchResults(BaseModel):
    """
    Encapsulates the raw retrieval results for a single query.

    Attributes:
        question_id: The identifier of the original question.
        question_str: The text of the original question.
        retrieved_sources: The list of sources found by the retrieval system.
    """

    question_id: str
    question_str: str
    retrieved_sources: List[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """
    Extends search results with a generated natural language answer.

    Attributes:
        answer: The answer generated by the LLM based on retrieved sources.
    """

    answer: str


T = TypeVar("T", bound=MinimalSearchResults)


class StudentSearchResults(BaseModel, Generic[T]):
    """
    A generic container for batch search results output.

    Attributes:
        search_results: A list of result objects (MinimalSearchResults or
            MinimalAnswer).
        k: The number of results requested per query.
    """

    search_results: List[T]
    k: int


class StudentSearchResultsAndAnswer(StudentSearchResults[MinimalAnswer]):
    """Specialized container for search results that include answers."""

    pass
